### PR TITLE
Sign language translator description and link

### PR DESCRIPTION
**Pull request by nomppy**

### CODE REVIEW

**Review by fanurs — APPROVED** [review]
LGTM.

Would you mind remind your team members to update the contributor list too? Thanks!

**Comment by nomppy** [comment]
> LGTM.
> 
> 
> 
> Would you mind remind your team members to update the contributor list too? Thanks!

@fanurs I'm not sure I understand what you mean. How do they update the contributor list?

**Comment by fanurs** [comment]
> > LGTM.
> > 
> > 
> > 
> > Would you mind remind your team members to update the contributor list too? Thanks!
> 
> @fanurs I'm not sure I understand what you mean. How do they update the contributor list?

Please see issue #4

**Comment by nomppy** [comment]
> > > LGTM.
> > > Would you mind remind your team members to update the contributor list too? Thanks!
> > 
> > 
> > @fanurs I'm not sure I understand what you mean. How do they update the contributor list?
> 
> Please see issue #4

Apologies, I thought you were referring to something else. I think we already did that.

**Comment by fanurs** [comment]
@spesthecat Oh, I mean to add that into this central repo (F22-projects). Thanks!

**Pull request merged**
